bot:
  token: "BOT_TOKEN"
  enable_multilanguage: true
  default_language: "ru"
  allowed_languages:
    - "ru"
    - "en"

database:
  host: "localhost"
  port: 5432
  user: "laravel"
  password: "password"
  dbname: "telegram"
  sslmode: "disable"